language: node_js
sudo: false
node_js:
  - "lts/*"
  - "stable"
  - "node"
install:
  - yarn
script:
  - yarn run ci
# after_success:
  # - codecov
notifications:
  email:
    on_success: change
    on_failure: always
